# Generated by Django 2.2.6 on 2019-11-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut', models.CharField(max_length=255)),
                ('flat_number', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('qu', models.IntegerField()),
                ('flat_number', models.CharField(max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('time1', models.DateTimeField(auto_now_add=True)),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser.Item')),
            ],
        ),
    ]
