# Generated by Django 2.2.6 on 2019-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0005_auto_20191104_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
