# Generated by Django 2.2.6 on 2019-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0007_auto_20191104_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
